export const COMODIDADES_PADRAO = [
  "Piscina",
  "Piscina infantil",
  "Parque aquático infantil",
  "Academia",
  "Restaurante",
  "Portaria 24h",
  "Sauna",
  "Salão de festas",
  "Quadra poliesportiva",
  "Playground",
  "Espaço gourmet",
  "Spa",
  "Coworking",
  "Pet place",
  "Bicicletário",
  "Gerador",
  "Segurança 24h",
  "Wi-fi nas áreas comuns",
  "Churrasqueira",
  "Elevador",
] as const;
