export const DETALHES_PADRAO = [
  "Mobiliado",
  "Vazio",
  "Com móveis fixos",
  "Armários planejados",
  "Garagem fixa",
  "Garagem rotativa",
  "Portaria digital",
  "Portaria 24h",
  "Elevador",
  "Fácil acesso",
  "Varanda",
  "Sacada gourmet",
  "Churrasqueira privativa",
  "Piscina privativa",
  "Lazer no térreo",
  "Lazer na cobertura (rooftop)",
  "Ar condicionado",
  "Lavanderia",
  "Área de serviço",
  "Depósito/Box",
  "Vista mar",
  "Aceita pet",
  "Interfone/vídeo porteiro",
  "Próximo a comércio",
] as const;
