import {
  Sofa,
  Box,
  Wrench,
  CarFront,
  RefreshCw,
  KeyRound,
  ShieldCheck,
  ArrowUpDown,
  Navigation,
  DoorOpen,
  UtensilsCrossed,
  Flame,
  Waves,
  Building2,
  Sparkles as SparklesIcon,
  Wind,
  Shirt,
  Archive,
  Package,
  Waves as WavesMar,
  PawPrint,
  Video,
  Store,
  CircleCheck,
} from "lucide-react";

export const ICONE_POR_DETALHE: Record<string, any> = {
  "Mobiliado": Sofa,
  "Vazio": Box,
  "Com móveis fixos": Wrench,
  "Armários planejados": Archive,
  "Garagem fixa": CarFront,
  "Garagem rotativa": RefreshCw,
  "Portaria digital": KeyRound,
  "Portaria 24h": ShieldCheck,
  "Elevador": ArrowUpDown,
  "Fácil acesso": Navigation,
  "Varanda": DoorOpen,
  "Sacada gourmet": UtensilsCrossed,
  "Churrasqueira privativa": Flame,
  "Piscina privativa": Waves,
  "Lazer no térreo": Building2,
  "Lazer na cobertura (rooftop)": SparklesIcon,
  "Ar condicionado": Wind,
  "Lavanderia": Shirt,
  "Área de serviço": Package,
  "Depósito/Box": Archive,
  "Vista mar": WavesMar,
  "Aceita pet": PawPrint,
  "Interfone/vídeo porteiro": Video,
  "Próximo a comércio": Store,
};

export function iconeDoDetalhe(nome: string) {
  return ICONE_POR_DETALHE[nome] ?? CircleCheck;
}
